### ISSUE TITLE
What differs uni-core from fairseq.

### ISSUE THREAD

**Issue by pengzhangzhi** [dptech-corp/Uni-Core#12]
This is absolute a good framework. But it's very similar to fariseq. I am wondering if there are anything different from fairseq that makes uni-core standing out, easy-to-use? fast? 

Best,
Zhangzhi

**Comment by guolinke** [comment]
As written in the readme, this is derived from fairseq. But Uni-Core only keeps its framework, excluding its many sequence models and many dependencies. This change is to make Uni-Core a pure and clean framework for developing various models. 
Besides, the efficiency is further improved.

**Comment by pengzhangzhi** [comment]
Sounds good! fairseq is really too tedious to follow.
