### ISSUE TITLE
How to install on cpu

### ISSUE THREAD

**Issue by Patricia1019** [dptech-corp/Uni-Core#17]
Hello,
I am doing a cpu-based project and I need to install Uni-core, but when I am running setup.py on my cpu machine, I met with _metadata-generation-failed_ error, so I wonder whether Uni-core can be installed on cpu? If yes, could you please tell me how to do this? If not, will you update a version which can be installed on cpu?
Thank you very much

**Comment by guolinke** [comment]
you can use ```python setup.py install --disable-cuda-ext```
